# Netlify Configuration for CareerAI

[build]
  command = "npm run build"

[build.environment]
  # Next.js optimization
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Disable Puppeteer download for Netlify
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"

# Enable Next.js Runtime
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"